---
title: "t4"
author: "Yoky"
date: "February 13, 2016"
output: md_document
---
(a). Odds of having diabetic complications among good diabetic control = 3/7 
Odds of having diabetic complications among poor diabetic control = 4/2 
Therefore, Odds Ratio = (3/7)/(4/2) = 3/14, which suggests that there is difference in complication rates between patients
with good diabetic control and those with poor control

(b). The Fisher's exact test is used here to analyse the  relationship between the two categorical variables in this contingency table. 
```{r}
Convictions <-
  matrix(c(3, 4, 7, 2),
         nrow = 2,
         dimnames =
           list(c("Good", "Poor"),
                c("Present", "Absent")))
Convictions
fisher.test(Convictions, alternative = "two.sided")
```
The result P-Value = 0.3024, suggesting that the difference between the two rates is not statistically significant on the 95% confidence interval.

(c). The reason is that the chi-square test only calculates an approximate P value, while Fisher's test always gives the exact P value. Chi-square test assumes that each cell has an expected frequency of five or more, but the Fisher's exact test has no such assumption and can be used regardless of how small the expected frequency is.
